### ISSUE TITLE
Heroku push rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by ghiculescu** [mattmanning/heroku-buildpack-ruby-jekyll#6]
I'm seeing this output when I try to push to Heroku today. (I wasn't getting this problem last time I pushed, about three days ago.)

```
[master 88b57ad] test
 2 files changed, 2 insertions(+), 1 deletions(-)
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 464 bytes, done.
Total 5 (delta 3), reused 0 (delta 0)

-----> Fetching custom git buildpack... done
 !     Heroku push rejected, no Cedar-supported app detected
```

My `heroku:config` includes this line:

```
BUILDPACK_URL: http://github.com/mattmanning/heroku-buildpack-ruby-jekyll.git
```

If I remove that (`heroku config:remove BUILDPACK_URL`), I can push with no issues. So I suspect it's something to do with the changes made in the last few days - though looking over them, I'm not sure what it could be. Any ideas?

**Comment by mytharcher** [comment]
Same with you @ssaunier . If any ruby version specified in `Gemfile` not match to Heroku provided ones, this would happen.

I got another error because the ruby version not specified:

```
remote:        Gem::InstallError: classifier-reborn requires Ruby version >= 1.9.3.
remote:        An error occurred while installing classifier-reborn (2.0.2), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install classifier-reborn -v '2.0.2'` succeeds before
remote:        bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby/Rack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to xxx.
remote: 
To git@heroku.com:xxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

and another error after specified ruby as `2.0.2`:

```
remote:        env: bundle: No such file or directory
remote:  !
remote:  !     Failed to generate site with jekyll.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby/Rack app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to xxx.
remote: 
To git@heroku.com:xxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

No idea how to fix this. Please help.

**Comment by mattmanning** [comment]
Any repo with a `Gemfile.lock` should get detected as a ruby app by Heroku.

I have updated the buildpack with the latest upstream Heroku Ruby buildpack and the current jekyll subcommands. I'm closing this issue, but please feel free to open a new one if you have further problems.
